# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "omniauth-goodreads"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ahmed El.Hussaini"]
  s.date = "2016-02-15"
  s.description = "OmniAuth strategy for Goodreads"
  s.email = "aelhussaini@gmail.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/omniauth-goodreads.rb",
    "lib/omniauth-goodreads/version.rb",
    "lib/omniauth/strategies/goodreads.rb",
    "omniauth-goodreads.gemspec"
  ]
  s.homepage = "http://github.com/sandboxws/omniauth-goodreads"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.14"
  s.summary = "OmniAuth strategy for Goodreads"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_runtime_dependency(%q<omniauth-oauth>, ["~> 1.1"])
      s.add_runtime_dependency(%q<multi_xml>, ["~> 0.6.0"])
    else
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<omniauth-oauth>, ["~> 1.1"])
      s.add_dependency(%q<multi_xml>, ["~> 0.6.0"])
    end
  else
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<omniauth-oauth>, ["~> 1.1"])
    s.add_dependency(%q<multi_xml>, ["~> 0.6.0"])
  end
end

